// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8P1rKx0DylOs8jtQKd9Yi-rBhTrIQdoo',
    appId: '1:230351859988:web:0117d0f423ca0be8b15201',
    messagingSenderId: '230351859988',
    projectId: 'test-project2-da338',
    authDomain: 'test-project2-da338.firebaseapp.com',
    storageBucket: 'test-project2-da338.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB41veIu0daQvXV4jiti5Cxuq6O4eddMGI',
    appId: '1:230351859988:android:decc29b1d2f8d984b15201',
    messagingSenderId: '230351859988',
    projectId: 'test-project2-da338',
    storageBucket: 'test-project2-da338.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEKXTRCqQDrVYTx6FA8jrVoumUZx-_L_8',
    appId: '1:230351859988:ios:b61064d18b91052bb15201',
    messagingSenderId: '230351859988',
    projectId: 'test-project2-da338',
    storageBucket: 'test-project2-da338.appspot.com',
    iosClientId: '230351859988-g3pmlusefl1olpe0ruelcngnpojs36i5.apps.googleusercontent.com',
    iosBundleId: 'com.example.exploreClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDEKXTRCqQDrVYTx6FA8jrVoumUZx-_L_8',
    appId: '1:230351859988:ios:b61064d18b91052bb15201',
    messagingSenderId: '230351859988',
    projectId: 'test-project2-da338',
    storageBucket: 'test-project2-da338.appspot.com',
    iosClientId: '230351859988-g3pmlusefl1olpe0ruelcngnpojs36i5.apps.googleusercontent.com',
    iosBundleId: 'com.example.exploreClone',
  );
}
